<?php
$pageTitle = 'Analytics Reports';
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/header.php';

$reports = [
    ['RPT-2026-3814', 'Sales', 'jsmith', '2026-08-07', 'completed'],
    ['RPT-2026-3813', 'Marketing', 'g.liu', '2026-08-07', 'completed'],
    ['RPT-2026-3812', 'Operations', 't.becker', '2026-08-07', 'pending'],
    ['RPT-2026-3811', 'Data Science', 's.chen', '2026-08-06', 'completed'],
    ['RPT-2026-3810', 'Finance', 'n.patel', '2026-08-06', 'completed'],
    ['RPT-2026-3809', 'Sales', 'jsmith', '2026-08-06', 'completed'],
    ['RPT-2026-3808', 'Security', 'l.fontaine', '2026-08-06', 'failed'],
    ['RPT-2026-3807', 'Engineering', 'j.carter', '2026-08-05', 'completed'],
    ['RPT-2026-3806', 'HR', 'p.sharma', '2026-08-05', 'completed'],
    ['RPT-2026-3805', 'Finance', 'n.patel', '2026-08-05', 'pending'],
    ['RPT-2026-3804', 'Marketing', 'g.liu', '2026-08-04', 'completed'],
    ['RPT-2026-3803', 'Data Science', 'a.okafor', '2026-08-04', 'completed'],
    ['RPT-2026-3802', 'Operations', 'm.webb', '2026-08-04', 'failed'],
    ['RPT-2026-3801', 'Sales', 'jsmith', '2026-08-03', 'completed'],
    ['RPT-2026-3800', 'Engineering', 'd.kim', '2026-08-03', 'completed'],
    ['RPT-2026-3799', 'Support', 'e.rodriguez', '2026-08-03', 'pending'],
];

$statusBadge = [
    'completed' => 'badge-green',
    'pending' => 'badge-yellow',
    'failed' => 'badge-red',
];
?>

<div class="card">
  <div class="toolbar">
    <div class="form-group">
      <label for="dateFrom">From</label>
      <input class="form-control" type="date" id="dateFrom" value="2026-07-01">
    </div>
    <div class="form-group">
      <label for="dateTo">To</label>
      <input class="form-control" type="date" id="dateTo" value="2026-08-08">
    </div>
    <div class="form-group">
      <label for="dept">Department</label>
      <select class="form-control" id="dept">
        <option>All departments</option>
        <option>Sales</option>
        <option>Marketing</option>
        <option>Engineering</option>
        <option>Finance</option>
        <option>Operations</option>
        <option>Data Science</option>
        <option>Security</option>
        <option>HR</option>
        <option>Support</option>
      </select>
    </div>
    <button class="btn" type="button" style="margin-left: auto;">Apply filters</button>
    <button class="btn btn-primary" type="button">Export CSV</button>
  </div>

  <div class="table-wrap" style="max-height: 480px; border: none; border-radius: 0;">
    <table class="table">
      <thead>
        <tr>
          <th>Report ID</th>
          <th>Department</th>
          <th>Generated By</th>
          <th>Date</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($reports as $r): ?>
        <tr>
          <td class="mono"><?php echo htmlspecialchars($r[0]); ?></td>
          <td><?php echo htmlspecialchars($r[1]); ?></td>
          <td><?php echo htmlspecialchars($r[2]); ?></td>
          <td><?php echo htmlspecialchars($r[3]); ?></td>
          <td><span class="badge <?php echo $statusBadge[$r[4]]; ?>"><?php echo htmlspecialchars($r[4]); ?></span></td>
          <td>
            <div class="cell-actions">
              <a class="btn btn-sm" href="/reports.php">View</a>
              <a class="btn btn-sm btn-ghost" href="/reports.php">Download</a>
            </div>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>

  <div class="pagination">
    <span class="page-info">Showing 16 of 3,947 reports</span>
    <button class="page-btn" disabled>&#8592; Prev</button>
    <button class="page-btn active">1</button>
    <button class="page-btn">2</button>
    <button class="page-btn">3</button>
    <button class="page-btn">4</button>
    <button class="page-btn">&#8230;</button>
    <button class="page-btn">247</button>
    <button class="page-btn">Next &#8594;</button>
  </div>
</div>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
